<a href="https://colab.research.google.com/github/JoeJacob2755/AI_Project/blob/Melonoma_Tumor_Size/melonoma_tumor_size.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [6]:
pd.set_option('display.float_format', '{:.6f}'.format)

In [7]:
path = 'https://raw.githubusercontent.com/JoeJacob2755/AI_Project/Melonoma_Tumor_Size/melanoma_tumor_size.csv'
mel1 = pd.read_csv(path)
mel1.head()

     mass_npea  size_npear  ...  damage_ratio  tumor_size
0  6930.900000 2919.020000  ...     39.362000   14.103000
1 15635.700000 4879.360000  ...     22.025300    2.648000
2 10376.200000 2613.880000  ...     29.996300    1.688000
3 13093.800000 4510.060000  ...     28.135400    3.796000
4  7545.210000 2882.360000  ...     35.020000   18.023000

[5 rows x 10 columns]

In [4]:
mel1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9146 entries, 0 to 9145
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mass_npea       9146 non-null   float64
 1   size_npear      9146 non-null   float64
 2   malign_ratio    9146 non-null   float64
 3   damage_size     9146 non-null   float64
 4   exposed_area    9146 non-null   float64
 5   std_dev_malign  9146 non-null   float64
 6   err_malign      9146 non-null   float64
 7   malign_penalty  9146 non-null   int64
 8   damage_ratio    9146 non-null   float64
 9   tumor_size      9146 non-null   float64
dtypes: float64(9), int64(1)
memory usage: 714.7 KB

In [8]:
mel1.describe().T

                     count           mean  ...            75%            max
mass_npea      9146.000000    9903.052174  ...   12119.950000   36995.400000
size_npear     9146.000000    3032.827837  ...    3830.745000   13535.000000
malign_ratio   9146.000000       0.303083  ...       0.343002       0.525300
damage_size    9146.000000     103.902118  ...     134.209000     346.420000
exposed_area   9146.000000 1372441.964798  ... 1693083.244850 4978616.041800
std_dev_malign 9146.000000     146.304239  ...     182.251500     528.890000
err_malign     9146.000000    3992.936256  ...    4664.577500   91983.700000
malign_penalty 9146.000000      69.849661  ...      91.000000     340.000000
damage_ratio   9146.000000      34.461652  ...      38.806075      46.546400
tumor_size     9146.000000       7.723348  ...      13.336000      20.999000

[10 rows x 8 columns]